name: asdf-firmware
on: [push]

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: firmware/asdf
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install gcc-avr binutils-avr avr-libc
      - run: sudo snap install cmake --classic
      - run: pip install -U sphinx sphinx-rtd-theme sphinx-autodoc-typehints
      - run: pip install -U sphinxcontrib-napoleon
      - run: pip install -U toml build
      - run: pip install pipenv

      # Create the build directories, make all targets, and copy
      # hex files to sphinx source directory for download links
      - run: pwd
      - run: ls -lR
      - run: bash ./make-targets.sh -a -p -i -s

      - run: mkdir public
      - run: sphinx-build -b html docs/source public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
