name: asdf-firmware
on: [push]

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    container: { image: alpine }
    defaults:
      run:
        shell: sh
    steps:
       - name: install_git_and_bash
         run: apk add bash git

       - name: checkout
         uses: actions/checkout@v2

       - run: apk add gcc-avr binutils-avr avr-libc
       - run: apk add cmake make
       - run: apk add python3 py3-pip
       - run: pip install -U sphinx sphinx-rtd-theme sphinx-autodoc-typehints
       - run: pip install -U sphinxcontrib-napoleon
       - run: pip install -U toml
       - run: pip install pipenv
       # Create the build directories, make all targets, and copy
       # hex files to sphinx source directory for download links
       - run: cd firmware/asdf; /bin/bash ./make-targets.sh -a -p -i -s
       - run: mkdir public
       - run: sphinx-build -b html firmware/asdf/docs/source public

       - name: Deploy
         uses: JamesIves/github-pages-deploy-action@v4
         with:
           folder: public
